"""
markdown.py — SCIENTIFIC_CONTEXT.md Renderer (EPIC 09)
======================================================
Renders a :class:`ScientificContext` into Obsidian-ready Markdown:

  * YAML frontmatter (type, evidence level, counts) for vault tooling
  * one section per context category, each paper as a ``[[WikiLink]]`` so
    the knowledge-graph extractor can ingest the note
  * contradictory papers use ``contradicts: [[...]]`` lines, giving the
    graph extractor a typed CONTRADICTS edge
  * per-provider retrieval provenance table at the end

``write_outputs`` persists ``<slug>.SCIENTIFIC_CONTEXT.md`` and a JSON
snapshot atomically (``.tmp`` → ``os.replace``, the repo-wide convention).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import List, Optional, Tuple

from core.utils.file_utils import atomic_write
from literature.context.models import (
    CATEGORY_DISPLAY,
    ContextCategory,
    ContextPaper,
    ScientificContext,
)
from literature.context.engine import DEFAULT_OUTPUT_DIR, slugify_title

_SECTION_ORDER: Tuple[ContextCategory, ...] = (
    ContextCategory.RELATED,
    ContextCategory.INFLUENTIAL,
    ContextCategory.REVIEW,
    ContextCategory.SYSTEMATIC_REVIEW,
    ContextCategory.META_ANALYSIS,
    ContextCategory.REPLICATION,
    ContextCategory.CONTRADICTORY,
    ContextCategory.FOLLOW_UP,
)

_WIKILINK_UNSAFE = re.compile(r"[\[\]#|]+")


def render_scientific_context(
    context: ScientificContext, max_per_section: Optional[int] = None
) -> str:
    """Render the full SCIENTIFIC_CONTEXT.md body for one expansion."""
    seed = context.seed
    lines: List[str] = []

    lines.extend(_frontmatter(context))
    lines.append(
        f"# Scientific Context — {_safe_text(seed.title or seed.doi or 'Imported Document')}"
    )
    lines.append("")
    lines.append(
        "> Auto-generated by the ROS Scientific Knowledge Expansion engine (EPIC 09). "
        "Every paper records the provider(s) that surfaced it."
    )
    lines.append("")

    lines.append("## Source Paper")
    lines.append("")
    lines.append(_seed_line(context))
    lines.append("")

    lines.append("## Evidence Strength")
    lines.append("")
    evidence = context.evidence
    lines.append(f"- **Level:** {evidence.level.value.upper()} (score {evidence.score:.2f})")
    for item in evidence.rationale:
        lines.append(f"- {item}")
    if evidence.signals:
        signal_text = ", ".join(
            f"{name}: {count}" for name, count in evidence.signals.items() if count
        )
        if signal_text:
            lines.append(f"- Signals: {signal_text}")
    lines.append("")

    buckets = context.category_lists()
    for category in _SECTION_ORDER:
        papers = buckets[category]
        if max_per_section is not None:
            papers = papers[:max_per_section]
        lines.append(f"## {CATEGORY_DISPLAY[category]}")
        lines.append("")
        if not papers:
            lines.append("_None retrieved._")
            lines.append("")
            continue
        for paper in papers:
            lines.extend(_paper_lines(category, paper))
        lines.append("")

    lines.append("## Retrieval Provenance")
    lines.append("")
    lines.extend(_provenance_table(context))
    lines.append("")

    return "\n".join(lines)


def write_outputs(
    context: ScientificContext, output_dir: Optional[Path] = None
) -> Tuple[Path, Path]:
    """Persist markdown + JSON outputs atomically. Returns (md_path, json_path)."""
    directory = Path(output_dir) if output_dir else DEFAULT_OUTPUT_DIR
    directory.mkdir(parents=True, exist_ok=True)

    slug = slugify_title(context.seed.title, context.seed.doi)
    md_path = directory / f"{slug}.SCIENTIFIC_CONTEXT.md"
    json_path = directory / f"{slug}.scientific_context.json"

    atomic_write(md_path, render_scientific_context(context))
    atomic_write(json_path, context.to_json())
    return md_path, json_path


# ── internals ────────────────────────────────────────────────────────────────


def _frontmatter(context: ScientificContext) -> List[str]:
    seed = context.seed
    counts = context.summary_counts()
    return [
        "---",
        f'title: "{_yaml_escape("Scientific Context — " + (seed.title or seed.doi or "Imported Document"))}"',
        "type: scientific_context",
        f"schema_version: {context.schema_version}",
        f"engine_version: {context.engine_version}",
        f"generated: {context.created_at}",
        f"seed_doi: {seed.doi or ''}",
        f"seed_year: {seed.year or ''}",
        f"evidence_level: {context.evidence.level.value}",
        f"evidence_score: {context.evidence.score:.2f}",
        f"paper_count: {context.total_papers}",
        f"category_counts: {json.dumps(counts, ensure_ascii=False)}",
        "---",
        "",
    ]


def _seed_line(context: ScientificContext) -> str:
    seed = context.seed
    parts = [f"- **{_safe_text(seed.title or '(untitled)')}**"]
    if seed.year:
        parts[0] += f" ({seed.year})"
    if seed.authors:
        parts.append(f"  - Authors: {_format_authors(seed.authors)}")
    if seed.venue:
        parts.append(f"  - Venue: {seed.venue}")
    if seed.doi:
        parts.append(f"  - DOI: [https://doi.org/{seed.doi}](https://doi.org/{seed.doi})")
    return "\n".join(parts)


def _paper_lines(category: ContextCategory, paper: ContextPaper) -> List[str]:
    record = paper.paper
    link = _wikilink(record.title)
    meta_bits: List[str] = []
    if record.year:
        meta_bits.append(str(record.year))
    if record.authors:
        meta_bits.append(_format_authors(record.authors))
    if record.venue:
        meta_bits.append(f"*{record.venue}*")
    if record.citation_count is not None:
        meta_bits.append(f"citations: {record.citation_count}")
    meta_bits.append(f"source: {', '.join(paper.sources) or record.source.value}")

    prefix = "- contradicts: " if category == ContextCategory.CONTRADICTORY else "- "
    head = f"{prefix}{link}"
    if meta_bits:
        head += f" — {' — '.join(meta_bits)}"

    lines = [head]
    if record.doi:
        lines.append(f"  - [https://doi.org/{record.doi}](https://doi.org/{record.doi})")
    if paper.rationale:
        lines.append(f"  - {_safe_text(paper.rationale)}")
    return lines


def _provenance_table(context: ScientificContext) -> List[str]:
    if not context.provider_provenance:
        return ["_No providers were queried._"]
    lines = [
        "| Provider | Source | Status | Retrieved | Latency (ms) | Queries |",
        "|---|---|---|---|---|---|",
    ]
    for prov in context.provider_provenance:
        queries = "; ".join(prov.queries) if prov.queries else "—"
        queries = _safe_text(queries)
        error = f" ({_safe_text(prov.error[:80])})" if prov.error else ""
        lines.append(
            f"| {prov.provider} | {prov.source} | {prov.status}{error} "
            f"| {prov.retrieved} | {prov.latency_ms:.0f} | {queries} |"
        )
    return lines


def _wikilink(title: str) -> str:
    return f"[[{_safe_text(title)}]]"


def _safe_text(text: str) -> str:
    cleaned = _WIKILINK_UNSAFE.sub(" ", (text or "").replace("\n", " "))
    return re.sub(r"\s+", " ", cleaned).strip()


def _format_authors(authors, max_authors: int = 3) -> str:
    names = [str(author) for author in authors if str(author).strip()]
    if not names:
        return ""
    if len(names) <= max_authors:
        return ", ".join(names)
    return ", ".join(names[:max_authors]) + " et al."


def _yaml_escape(text: str) -> str:
    return (text or "").replace('"', "'")
